"""Emit data/EU/eu_nutrient_mapping.csv.

Auditable mapping table between USDA canonical nutrient names and the source
columns / codes in Ciqual (FR), CoFID (UK) and NEVO (NL). Drives the EU
fallback dataset loader.

One row per output nutrient. When a USDA equivalent exists, `usda_name` is
populated and downstream loaders should use it as the JSONB key. When the
nutrient has no USDA equivalent (e.g. Iodine, Chloride, Biotin, Salt), the row
is marked EU-only and the loader stores it under `eu_canonical_name`.
"""

from __future__ import annotations
import csv
from pathlib import Path

OUT = Path("data/EU/eu_nutrient_mapping.csv")

# (usda_name, usda_id, usda_unit, ciqual_col, cofid_sheet, cofid_col,
#  nevo_code, nevo_component, eu_canonical_name, notes)
# - empty string means "not available in that source"
# - For CoFID FAs we use the "per 100g food" sheets (1.8/1.10/1.12), not per-100g-FA.
# - Vitamin A, IU is computed (USDA-pre-2001 formula) from retinol + beta-carotene.

ROWS: list[tuple[str, str, str, str, str, str, str, str, str, str]] = [
    # --- energy ---
    ("Energy", "268", "kJ",
     "Energy, Regulation EU No 1169 2011 (kJ 100g)",
     "1.3 Proximates", "kJ",
     "ENERCJ", "Energy kJ",
     "", ""),
    ("Energy, kcal", "208", "kcal",
     "Energy, Regulation EU No 1169 2011 (kcal 100g)",
     "1.3 Proximates", "kcal",
     "ENERCC", "Energy kcal",
     "", "Added key; USDA stores kcal under id 208 but our table only kept kJ"),

    # --- proximates ---
    ("Water", "255", "g",
     "Water (g 100g)", "1.3 Proximates", "Water", "WATER", "Water total", "", ""),
    ("Protein", "203", "g",
     "Protein (g 100g)", "1.3 Proximates", "Protein", "PROT", "Protein total", "", ""),
    ("Total lipid (fat)", "204", "g",
     "Fat (g 100g)", "1.3 Proximates", "Fat", "FAT", "Fat total", "", ""),
    ("Carbohydrate, by difference", "205", "g",
     "Carbohydrate (g 100g)", "1.3 Proximates", "Carbohydrate",
     "CHO", "Carbohydrate available", "",
     "EU values are available-carb (post-fibre); USDA is by-difference. Close enough for matcher fallback"),
    ("Fiber, total dietary", "291", "g",
     "Fibres (g 100g)", "1.3 Proximates", "AOAC fibre", "FIBT", "Fibre dietary total", "", ""),
    ("Ash", "207", "g",
     "Ash (g 100g)", "", "", "ASH", "Ash", "", ""),
    ("Alcohol, ethyl", "221", "g",
     "Alcohol (g 100g)", "1.3 Proximates", "Alcohol", "ALC", "Alcohol total", "", ""),

    # --- sugars ---
    ("Sugars, total", "269", "g",
     "Sugars (g 100g)", "1.3 Proximates", "Total sugars", "SUGAR", "Sugars total", "", ""),
    ("Starch", "209", "g",
     "Starch (g 100g)", "1.3 Proximates", "Starch", "STARCH", "Starch total", "", ""),
    ("Sucrose", "210", "g",
     "Sucrose (g 100g)", "1.3 Proximates", "Sucrose", "", "", "", ""),
    ("Glucose (dextrose)", "211", "g",
     "Glucose (g 100g)", "1.3 Proximates", "Glucose", "", "", "", ""),
    ("Fructose", "212", "g",
     "Fructose (g 100g)", "1.3 Proximates", "Fructose", "", "", "", ""),
    ("Lactose", "213", "g",
     "Lactose (g 100g)", "1.3 Proximates", "Lactose", "", "", "", ""),
    ("Maltose", "214", "g",
     "Maltose (g 100g)", "1.3 Proximates", "Maltose", "", "", "", ""),
    ("Galactose", "287", "g",
     "Galactose (g 100g)", "1.3 Proximates", "Galactose", "", "", "", ""),

    # --- minerals ---
    ("Calcium, Ca", "301", "mg",
     "Calcium (mg 100g)", "1.4 Inorganics", "Calcium", "CA", "Calcium", "", ""),
    ("Iron, Fe", "303", "mg",
     "Iron (mg 100g)", "1.4 Inorganics", "Iron", "FE", "Iron total", "", ""),
    ("Magnesium, Mg", "304", "mg",
     "Magnesium (mg 100g)", "1.4 Inorganics", "Magnesium", "MG", "Magnesium", "", ""),
    ("Phosphorus, P", "305", "mg",
     "Phosphorus (mg 100g)", "1.4 Inorganics", "Phosphorus", "P", "Phosphorus", "", ""),
    ("Potassium, K", "306", "mg",
     "Potassium (mg 100g)", "1.4 Inorganics", "Potassium", "K", "Potassium", "", ""),
    ("Sodium, Na", "307", "mg",
     "Sodium (mg 100g)", "1.4 Inorganics", "Sodium", "NaN", "Sodium", "",
     "NEVO code is literally 'NaN' (sodium) — guard against pandas auto-parsing"),
    ("Zinc, Zn", "309", "mg",
     "Zinc (mg 100g)", "1.4 Inorganics", "Zinc", "ZN", "Zinc", "", ""),
    ("Copper, Cu", "312", "mg",
     "Copper (mg 100g)", "1.4 Inorganics", "Copper", "CU", "Copper", "", ""),
    ("Manganese, Mn", "315", "mg",
     "Manganese (mg 100g)", "1.4 Inorganics", "Manganese", "", "", "", ""),
    ("Selenium, Se", "317", "ug",
     "Selenium (µg 100g)", "1.4 Inorganics", "Selenium", "SE", "Selenium total", "",
     "Unit harmonisation: µg -> ug"),

    # --- EU-only minerals (no USDA id) ---
    ("", "", "",
     "Chloride (mg 100g)", "1.4 Inorganics", "Chloride", "", "",
     "Chloride", "EU-only — USDA does not track chloride"),
    ("", "", "",
     "Iodine (µg 100g)", "1.4 Inorganics", "Iodine", "ID", "Iodine",
     "Iodine, I", "EU-only — USDA SR does not track iodine"),
    ("", "", "",
     "Salt (g 100g)", "", "", "", "",
     "Salt", "EU-only convenience field (= sodium × 2.5). Skip on load — sodium already captured"),

    # --- vitamins ---
    ("Retinol", "319", "ug",
     "Retinol (µg 100g)", "1.6 Vitamin Fractions", "All-trans-retinol",
     "RETOL", "Retinol", "",
     "CoFID 'All-trans-retinol' is the dominant form; close to total retinol"),
    ("Vitamin A, RAE", "320", "ug",
     "Vitamin A activity, retinol equivalent (µg 100mg)",
     "1.5 Vitamins", "Total retinol equivalent",
     "VITA_RAE", "Retinol activity equivalents (RAE)", "",
     "CoFID uses RE (older formula, β-carotene/6); Ciqual+NEVO use RAE (newer, /12). Diverge by ~2x for carotene-rich foods; flag in source_code"),
    ("Carotene, beta", "321", "ug",
     "Beta-carotene (µg 100g)", "1.6 Vitamin Fractions", "Beta-carotene",
     "CARTBTOT", "Beta-carotene", "", ""),
    ("Carotene, alpha", "322", "ug",
     "", "1.6 Vitamin Fractions", "Alpha-carotene",
     "CARTA", "Alpha-carotene", "", ""),
    ("Cryptoxanthin, beta", "334", "ug",
     "", "1.6 Vitamin Fractions", "Cryptoxanthins",
     "CRYPXB", "Beta-cryptoxanthin", "",
     "CoFID 'Cryptoxanthins' is sum of α+β; we map to β as the dominant form. Flag in source_code"),
    ("Lycopene", "337", "ug",
     "", "1.6 Vitamin Fractions", "Lycopene", "LYCPN", "Lycopene", "", ""),
    ("Lutein + zeaxanthin", "338", "ug",
     "", "1.6 Vitamin Fractions", "Lutein",
     "LUTN", "Lutein", "",
     "CoFID + NEVO report lutein only; zeaxanthin tracked separately in NEVO (ZEA). Sum on load when both present"),
    ("Vitamin A, IU", "318", "IU",
     "", "", "", "", "",
     "",
     "COMPUTED: retinol_ug/0.3 + beta_carotene_ug/0.6 (USDA pre-2001 formula). source_code='computed_from_retinol+beta_carotene'"),

    ("Vitamin D (D2 + D3)", "328", "ug",
     "Vitamin D (µg 100g)", "1.5 Vitamins", "Total Vitamin D",
     "VITD", "Vitamin D total", "", ""),
    ("Vitamin D2 (ergocalciferol)", "325", "ug",
     "Vitamin D2 (ergocalciferol) (µg 100g)", "", "",
     "ERGCAL", "Ergocalciferol (Vit D2)", "", ""),
    ("Vitamin D3 (cholecalciferol)", "326", "ug",
     "Vitamin D3 (cholecalciferol) (µg 100g)", "1.6 Vitamin Fractions", "Cholecalciferol",
     "CHOCAL", "Cholecalciferol (Vit D3)", "", ""),

    ("Vitamin E (alpha-tocopherol)", "323", "mg",
     "Alpha-tocopherol (vitamine E)(mg 100g)", "1.6 Vitamin Fractions", "Alpha-tocopherol",
     "TOCPHA", "Alpha-tocopherol", "", ""),
    ("Tocopherol, beta", "341", "mg",
     "", "1.6 Vitamin Fractions", "Beta-tocopherol", "TOCPHB", "Beta-tocopherol", "", ""),
    ("Tocopherol, gamma", "342", "mg",
     "", "1.6 Vitamin Fractions", "Gamma-tocopherol", "TOCPHG", "Gamma-tocopherol", "", ""),
    ("Tocopherol, delta", "343", "mg",
     "", "1.6 Vitamin Fractions", "Delta-tocopherol", "TOCPHD", "Delta-tocopherol", "", ""),
    ("Tocotrienol, alpha", "344", "mg",
     "", "1.6 Vitamin Fractions", "Alpha-tocotrienol", "", "", "", ""),
    ("Tocotrienol, gamma", "346", "mg",
     "", "1.6 Vitamin Fractions", "Gamma-tocotrienol", "", "", "", ""),

    ("Vitamin K (phylloquinone)", "430", "ug",
     "Vitamin K1 (µg 100g)", "1.5 Vitamins", "Phylloquinone",
     "VITK1", "Vitamin K1", "", ""),
    # NEVO/Ciqual also have K2 -> store under USDA Menaquinone-4 (closest match)
    ("Menaquinone-4", "428", "ug",
     "Vitamin K2 (µg 100g)", "", "",
     "VITK2", "Vitamin K2", "",
     "Ciqual+NEVO 'K2' is total menaquinones; USDA id 428 is specifically MK-4. Close-enough mapping; flag in source_code"),

    ("Vitamin C, total ascorbic acid", "401", "mg",
     "Vitamin C (mg 100g)", "1.5 Vitamins", "Vitamin C", "VITC", "Ascorbic acid (Vit C)", "", ""),
    ("Thiamin", "404", "mg",
     "Vitamin B1 or Thiamin (mg 100g)", "1.5 Vitamins", "Thiamin", "THIA", "Thiamin (Vit B1)", "", ""),
    ("Riboflavin", "405", "mg",
     "Vitamin B2 or Riboflavin (mg 100g)", "1.5 Vitamins", "Riboflavin", "RIBF", "Riboflavin (Vit B2)", "", ""),
    ("Niacin", "406", "mg",
     "Vitamin B3 or Niacin (mg 100g)", "1.5 Vitamins", "Niacin", "NIA", "Niacin (Vit B3)", "", ""),
    ("Pantothenic acid", "410", "mg",
     "Vitamin B5 or Pantothenic acid (mg 100g)", "1.5 Vitamins", "Pantothenate",
     "", "", "", "NEVO does not track B5"),
    ("Vitamin B-6", "415", "mg",
     "Vitamin B6 (mg 100g)", "1.5 Vitamins", "Vitamin B6", "VITB6", "Pyridoxin (Vit B6)", "", ""),
    ("Folate, DFE", "435", "ug",
     "Vitamin B9 or total folates, dietary folate equivalents, DFE (µg 100g)", "", "",
     "FOL", "Dietary folate equivalents", "", ""),
    ("Folate, total", "417", "ug",
     "Vitamin B9 or total folates (µg 100g)", "1.5 Vitamins", "Folate",
     "", "", "",
     "NEVO splits into FOLFD (food) + FOLAC (synthetic); use FOLFD here"),
    ("Folate, food", "432", "ug",
     "Intrinsic folate (µg 100 g)", "", "",
     "FOLFD", "Folate food", "", ""),
    ("Folic acid", "431", "ug",
     "Folic acid (enrichment) (µg 100g)", "", "",
     "FOLAC", "Folic acid synthetic", "", ""),
    ("Vitamin B-12", "418", "ug",
     "Vitamin B12 (µg 100g)", "1.5 Vitamins", "Vitamin B12", "VITB12", "Cobalamin (Vit B12)", "", ""),

    # --- EU-only vitamins ---
    ("", "", "",
     "", "1.5 Vitamins", "Biotin", "", "",
     "Biotin", "EU-only — USDA SR does not track biotin"),
    ("", "", "",
     "", "1.6 Vitamin Fractions", "25-hydroxy vitamin D3",
     "CHOCALOH", "25-hydroxycholecalciferol (25OHVitD3)",
     "25-hydroxy-D3", "EU-only — USDA does not separate 25-OH-D3"),
    ("", "", "",
     "", "", "", "ZEA", "Zeaxanthin",
     "Zeaxanthin", "NEVO-only — USDA reports as 'Lutein + zeaxanthin' combined"),

    # --- cholesterol & fat clusters ---
    ("Cholesterol", "601", "mg",
     "Cholesterol (mg 100g)", "1.3 Proximates", "Cholesterol",
     "CHORL", "Cholesterol", "", ""),
    ("Fatty acids, total saturated", "606", "g",
     "FA saturated (g 100g)", "1.3 Proximates", "Saturated fatty acids per 100g food",
     "FASAT", "Fatty acids saturated total", "", ""),
    ("Fatty acids, total monounsaturated", "645", "g",
     "FA mono (g 100g)", "1.3 Proximates", "Monounsaturated fatty acids per 100g food",
     "FAMSCIS", "Fatty acids monounsaturated cis total", "",
     "NEVO is cis-only; Ciqual/CoFID are total MUFA (cis+trans). Diverges only for partially-hydrogenated fats"),
    ("Fatty acids, total polyunsaturated", "646", "g",
     "FA poly (g 100g)", "1.3 Proximates", "Polyunsaturated fatty acids per 100g food",
     "FAPU", "Fatty acids total polyunsaturated total", "", ""),
    ("Fatty acids, total trans", "605", "g",
     "", "1.3 Proximates", "Total Trans fatty acids per 100g food",
     "FATRS", "Fatty acids trans total", "", ""),

    # --- individual SFA (per 100g food) ---
    ("4:0", "607", "g",
     "FA 4:0 (g 100g)", "1.8 (SFA per 100gFood)", "Butanoic acid per 100g food",
     "F4:0", "C4:0", "", ""),
    ("6:0", "608", "g",
     "FA 6:0 (g 100g)", "1.8 (SFA per 100gFood)", "Hexanoic acid per 100g food",
     "F6:0", "C6:0", "", ""),
    ("8:0", "609", "g",
     "FA 8:0 (g 100g)", "1.8 (SFA per 100gFood)", "Octanoic acid per 100g food",
     "F8:0", "C8:0", "", ""),
    ("10:0", "610", "g",
     "FA 10:0 (g 100g)", "1.8 (SFA per 100gFood)", "Decanoic acid per 100g food",
     "F10:0", "C10:0", "", ""),
    ("12:0", "611", "g",
     "FA 12:0 (g 100g)", "1.8 (SFA per 100gFood)", "Dodecanoic acid per 100g food",
     "F12:0", "C12:0", "", ""),
    ("13:0", "696", "g",
     "", "1.8 (SFA per 100gFood)", "Tridecanoic acid per 100g food",
     "F13:0", "C13:0", "", ""),
    ("14:0", "612", "g",
     "FA 14:0 (g 100g)", "1.8 (SFA per 100gFood)", "Tetradecanoic acid per 100g food",
     "F14:0", "C14:0", "", ""),
    ("15:0", "652", "g",
     "", "1.8 (SFA per 100gFood)", "Pentadecanoic acid per 100g food",
     "F15:0", "C15:0", "", ""),
    ("16:0", "613", "g",
     "FA 16:0 (g 100g)", "1.8 (SFA per 100gFood)", "Hexadecanoic acid per 100g food",
     "F16:0", "C16:0", "", ""),
    ("17:0", "653", "g",
     "", "1.8 (SFA per 100gFood)", "Heptadecanoic acid per 100g food",
     "F17:0", "C17:0", "", ""),
    ("18:0", "614", "g",
     "FA 18:0 (g 100g)", "1.8 (SFA per 100gFood)", "Octadecanoic acid per 100g food",
     "F18:0", "C18:0", "", ""),
    ("20:0", "615", "g",
     "", "1.8 (SFA per 100gFood)", "Eicosanoic acid per 100g food",
     "F20:0", "C20:0", "", ""),
    ("22:0", "624", "g",
     "", "1.8 (SFA per 100gFood)", "Docosanoic acid per 100g food",
     "F22:0", "C22:0", "", ""),
    ("24:0", "654", "g",
     "", "1.8 (SFA per 100gFood)", "Tetracosanoic acid per 100g food",
     "F24:0", "C24:0", "", ""),

    # --- individual MUFA (per 100g food) ---
    ("16:1 undifferentiated", "626", "g",
     "", "1.10 (MUFA per 100gFood)", "Hexadecenoic acid per 100g food", "", "", "",
     "NEVO has F16:1CIS (cis only)"),
    ("18:1 undifferentiated", "617", "g",
     "FA 18:1 n-9 cis (g 100g)", "1.10 (MUFA per 100gFood)", "Octadecenoic acid per 100g food",
     "F18:1CIS", "C18:1 cis", "",
     "Ciqual is 18:1 n-9 cis specifically; CoFID is total octadecenoic; NEVO is total cis. Approximate"),
    ("20:1", "628", "g",
     "", "1.10 (MUFA per 100gFood)", "Eicosenoic acid per 100g food",
     "F20:1CIS", "C20:1 cis", "", ""),
    ("22:1 undifferentiated", "630", "g",
     "", "1.10 (MUFA per 100gFood)", "Docosenoic acid per 100g food",
     "F22:1CIS", "C22:1 cis", "", ""),
    ("24:1 c", "671", "g",
     "", "1.10 (MUFA per 100gFood)", "cis Tetracosenoic acid per 100g food",
     "F24:1CIS", "C24:1 cis", "", ""),

    # --- individual PUFA n-6/n-3 ---
    ("18:2 n-6 c,c", "675", "g",
     "FA 18:2 9c,12c (n-6) (g 100g)", "1.12 (PUFA per 100gFood)", "cis n-6 Octadecadienoic acid per 100g food",
     "F18:2CN6", "C18:2 n-6 (linoleic acid)", "", ""),
    ("18:3 n-3 c,c,c (ALA)", "851", "g",
     "FA 18:3 c9,c12,c15 (n-3) (g 100g)", "1.12 (PUFA per 100gFood)", "cis n-3 Octadecatrienoic acid per 100g food",
     "F18:3CN3", "C18:3 n-3 cis (ALA)", "", ""),
    ("18:3 n-6 c,c,c", "685", "g",
     "", "1.12 (PUFA per 100gFood)", "cis n-6 Octadecatrienoic acid per 100g food",
     "F18:3CN6", "C18:3 n-6 cis", "", ""),
    ("18:4", "627", "g",
     "", "1.12 (PUFA per 100gFood)", "Octadecatetraenoic acid per 100g food",
     "F18:4CN3", "C18:4 n-3 cis", "",
     "NEVO/CoFID report 18:4 n-3 (stearidonic); USDA id 627 is undifferentiated"),
    ("20:2 n-6 c,c", "672", "g",
     "", "1.12 (PUFA per 100gFood)", "cis n-6 Eicosadienoic acid per 100g food",
     "F20:2CN6", "C20:2 n-6 cis", "", ""),
    ("20:3 n-6", "853", "g",
     "", "1.12 (PUFA per 100gFood)", "cis n-6 Eicosatrienoic acid per 100g food",
     "F20:3CN6", "C20:3 n-6 cis", "", ""),
    ("20:3 n-3", "852", "g",
     "", "", "",
     "F20:3CN3", "C20:3 n-3 cis", "", ""),
    ("20:4 n-6", "855", "g",
     "FA 20:4 5c,8c,11c,14c (n-6) (g 100g)", "1.12 (PUFA per 100gFood)", "cis n-6 Eicosatetraenoic acid per 100g food",
     "F20:4CN6", "C20:4 n-6 cis", "", ""),
    ("20:5 n-3 (EPA)", "629", "g",
     "FA 20:5 5c,8c,11c,14c,17c (n-3) EPA (g 100g)", "1.12 (PUFA per 100gFood)", "cis n-3 Eicosapentaenoic acid per 100g food",
     "F20:5CN3", "C20:5 n-3 cis (EPA)", "", ""),
    ("21:5", "857", "g",
     "", "1.12 (PUFA per 100gFood)", "cis n-3 Heneicosapentaenoic acid per 100g food",
     "F21:5CN3", "C21:5 n-3 all-cis", "", ""),
    ("22:4", "858", "g",
     "", "1.12 (PUFA per 100gFood)", "cis n-6 Docosatetraenoic acid per 100g food",
     "F22:4CN6", "C22:4 n-6 cis", "", ""),
    ("22:5 n-3 (DPA)", "631", "g",
     "", "1.12 (PUFA per 100gFood)", "cis n-3 Docosapentaenoic acid per 100g food",
     "F22:5CN3", "C22:5 n-3 cis (DPA)", "", ""),
    ("22:6 n-3 (DHA)", "621", "g",
     "FA 22:6 4c,7c,10c,13c,16c,19c (n-3) DHA (g 100g)", "1.12 (PUFA per 100gFood)", "cis n-3 Docosahexaenoic acid (DHA) per 100g food",
     "F22:6CN3", "C22:6 n-3 cis (DHA)", "", ""),

    # --- phytosterols ---
    ("Phytosterols", "636", "mg",
     "", "1.13 Phytosterols", "Total Phytosterols", "", "", "", ""),
    ("Beta-sitosterol", "641", "mg",
     "", "1.13 Phytosterols", "Beta-sitosterol", "", "", "", ""),
    ("Campesterol", "639", "mg",
     "", "1.13 Phytosterols", "Campesterol", "", "", "", ""),
    ("Stigmasterol", "638", "mg",
     "", "1.13 Phytosterols", "Stigmasterol", "", "", "", ""),

    # --- EU-only proximates ---
    ("", "", "",
     "Organic acids (g 100g)", "1.14 Organic Acids", "",
     "OA", "Organic acids total",
     "Organic acids, total",
     "EU-only. CoFID 1.14 has Citric + Malic individually but no total"),
    ("", "", "",
     "Polyols (g 100g)", "", "",
     "POLYL", "Polyols total",
     "Polyols", "EU-only — USDA does not aggregate sugar alcohols"),
    ("", "", "",
     "", "1.3 Proximates", "Non-starch polysaccharide", "", "",
     "Non-starch polysaccharide", "CoFID-only — Englyst method fibre proxy"),
    ("", "", "",
     "", "", "", "NVSUGAF", "Free sugars",
     "Free sugars", "NEVO-only — WHO definition; valuable for Nutri-Score"),
    ("", "", "",
     "", "", "", "PROTPL", "Protein plant",
     "Protein, plant", "NEVO-only"),
    ("", "", "",
     "", "", "", "PROTAN", "Protein animal",
     "Protein, animal", "NEVO-only"),
    ("", "", "",
     "", "", "", "HAEM", "Iron haem",
     "Iron, haem", "NEVO-only"),
    ("", "", "",
     "", "", "", "NHAEM", "Iron non-haem",
     "Iron, non-haem", "NEVO-only"),
]

HEADER = [
    "usda_name", "usda_id", "usda_unit",
    "ciqual_column",
    "cofid_sheet", "cofid_column",
    "nevo_code", "nevo_component",
    "eu_canonical_name",
    "notes",
]


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(HEADER)
        for row in ROWS:
            w.writerow(row)
    n_usda = sum(1 for r in ROWS if r[0])
    n_euonly = sum(1 for r in ROWS if not r[0])
    print(f"Wrote {OUT} — {len(ROWS)} rows ({n_usda} USDA-mapped, {n_euonly} EU-only)")


if __name__ == "__main__":
    main()
